In [79]:
from sqlalchemy import create_engine
import pandas as pd
from ml_experiments.analyze import get_df_runs_from_mlflow_sql, get_missing_entries, get_common_combinations, get_df_with_combinations
import plotly.express as px
from itertools import product
import time
import numpy as np
from pathlib import Path

# Save Results

## Load mlflow runs

In [81]:
db_path = Path().resolve().parent
db_name = 'ml_experiments.db'
url = f'sqlite:////{str(db_path)}/ml_experiments.db'
engine = create_engine(url)
query = 'SELECT experiments.name from experiments'
experiment_names = pd.read_sql(query, engine)['name'].tolist()
experiment_names

['Default', 'blob_time', 'hypercube_perf', 'real_perf']

In [82]:
experiments_names = [
    'blob_time',
]

In [83]:
params_columns = [
    'model_nickname',
    'n_samples',
    'n_features',
    'seed_dataset',
    'n_cores',
    'n_jobs',
]

In [84]:
latest_metrics_columns = [
    'fit_model_return_elapsed_time',
    'max_memory_used'
]

In [85]:
tags_columns = [
    'raised_exception',
    'EXCEPTION'
]

In [86]:
runs_columns = ['run_uuid', 'status', 'start_time', 'end_time']
experiments_columns = []
other_table = 'params'
other_table_keys = params_columns
df_params = get_df_runs_from_mlflow_sql(engine, runs_columns=runs_columns, experiments_columns=experiments_columns, experiments_names=experiments_names, other_table=other_table, other_table_keys=other_table_keys)
df_latest_metrics = get_df_runs_from_mlflow_sql(engine, runs_columns=['run_uuid'], experiments_columns=experiments_columns, experiments_names=experiments_names, other_table='latest_metrics', other_table_keys=latest_metrics_columns)
df_tags = get_df_runs_from_mlflow_sql(engine, runs_columns=['run_uuid'], experiments_columns=experiments_columns, experiments_names=experiments_names, other_table='tags', other_table_keys=tags_columns)

In [87]:
df_runs_raw = df_params.join(df_latest_metrics)
df_runs_raw = df_runs_raw.join(df_tags)

In [88]:
df_runs_raw

key,status,start_time,end_time,model_nickname,n_cores,n_features,n_jobs,n_samples,seed_dataset,fit_model_return_elapsed_time,max_memory_used,raised_exception
run_uuid,,,,,,,,,,,,
a2a179865078473a89620feec5df8b66,FINISHED,1738176052572,1738176052702,HDBSCAN,4,100,4,100,0,0.016728,331.852,False
d2395c43c6de4ecb872d9cb1b2363e13,FINISHED,1738174076274,1738174077347,CoHiRF,4,100,4,100,0,0.974811,334.748,False

## Delete duplicate runs (if any) and complete some models that cannot run with some datasets

In [89]:
non_duplicate_columns = [
    'model_nickname',
    'n_samples',
    'n_features',
    'seed_dataset',
]
df_runs = df_runs_raw.dropna(axis=0, how='all', subset=['fit_model_return_elapsed_time']).copy()
df_runs = df_runs.loc[(~df_runs.duplicated(non_duplicate_columns))]

In [90]:
no_run_time = np.inf
df_runs_timed_out = df_runs_raw.copy()
# df_runs_timed_out = df_runs_timed_out.loc[df_runs_timed_out['EXCEPTION'] == 'FunctionTimedOut']
df_runs_timed_out = df_runs_timed_out.loc[(~df_runs_timed_out.duplicated(non_duplicate_columns))]
df_runs_timed_out['fit_model_return_elapsed_time'] = no_run_time
df_runs = pd.concat([df_runs, df_runs_timed_out])

In [91]:
status = 'FAILED'
no_run_memory = np.inf
raised_exception = True
EXCEPTION = 'NoRun'
start_time = time.time() * 1000
end_time = time.time() * 1000

In [92]:
# IRFLLRR do not run with n_samples > 14427
model_nickname = 'IRFLLRR'
n_samples = ['14427', '50000']
n_features = ['100', '347', '1202', '4163', '14427', '50000']
seeds_datasets = [str(i) for i in range(10)]
combinations = product(n_samples, n_features, seeds_datasets)
df_cat = []
indexes = []
for n_sample, n_feature, seed in combinations:
    df = {}
    index = f'{model_nickname}_{n_sample}_{n_feature}'
    df['status'] = status
    df['start_time'] = start_time
    df['end_time'] = end_time
    df['model_nickname'] = model_nickname
    df['n_features'] = n_feature
    df['n_samples'] = n_sample
    df['seed_dataset'] = seed
    df['fit_model_return_elapsed_time'] = no_run_time
    df['max_memory_used'] = no_run_memory
    df['EXCEPTION'] = EXCEPTION
    df['raised_exception'] = raised_exception
    df_cat.append(df)
    indexes.append(index)
df_no_run = pd.DataFrame(df_cat, index=indexes)
df_runs = pd.concat([df_runs, df_no_run])

In [93]:
# KMeansProj do not run with (14427,14427), (14427,50000), (50000,14427), (50000,50000)
model_nickname = 'KMeansProj'
n_samples = ['14427', '50000']
n_features = ['14427', '50000']
seeds_datasets = [str(i) for i in range(10)]
combinations = product(n_samples, n_features, seeds_datasets)
df_cat = []
indexes = []
for n_sample, n_feature, seed in combinations:
    df = {}
    index = f'{model_nickname}_{n_sample}_{n_feature}'
    df['status'] = status
    df['start_time'] = start_time
    df['end_time'] = end_time
    df['model_nickname'] = model_nickname
    df['n_features'] = n_feature
    df['n_samples'] = n_sample
    df['seed_dataset'] = seed
    df['fit_model_return_elapsed_time'] = no_run_time
    df['max_memory_used'] = no_run_memory
    df['EXCEPTION'] = EXCEPTION
    df['raised_exception'] = raised_exception
    df_cat.append(df)
    indexes.append(index)
df_no_run = pd.DataFrame(df_cat, index=indexes)
df_runs = pd.concat([df_runs, df_no_run])

In [94]:
# HDBSCAN do not run with (14427,14427), (14427,50000), and n_samples = 50000 n_features > 347
model_nickname = 'HDBSCAN'
n_samples = ['50000']
n_features = ['347', '1202', '4163', '14427', '50000']
seeds_datasets = [str(i) for i in range(10)]
combinations = list(product(n_samples, n_features, seeds_datasets))
combinations_samples_features = [('14427', '14427'), ('14427', '50000')]
for samples, features in combinations_samples_features:
    combinations += list(product([samples], [features], seeds_datasets))
df_cat = []
indexes = []
for n_sample, n_feature, seed in combinations:
    df = {}
    index = f'{model_nickname}_{n_sample}_{n_feature}'
    df['status'] = status
    df['start_time'] = start_time
    df['end_time'] = end_time
    df['model_nickname'] = model_nickname
    df['n_features'] = n_feature
    df['n_samples'] = n_sample
    df['seed_dataset'] = seed
    df['fit_model_return_elapsed_time'] = no_run_time
    df['max_memory_used'] = no_run_memory
    df['EXCEPTION'] = EXCEPTION
    df['raised_exception'] = raised_exception
    df_cat.append(df)
    indexes.append(index)
df_no_run = pd.DataFrame(df_cat, index=indexes)
df_runs = pd.concat([df_runs, df_no_run])

In [95]:
# SpectralSubspaceRandomization do not run with n_samples > 50000
model_nickname = 'SpectralSubspaceRandomization'
n_samples = ['50000']
n_features = ['100', '347', '1202', '4163', '14427', '50000']
seeds_datasets = [str(i) for i in range(10)]
combinations = list(product(n_samples, n_features, seeds_datasets))
df_cat = []
indexes = []
for n_sample, n_feature, seed in combinations:
    df = {}
    index = f'{model_nickname}_{n_sample}_{n_feature}'
    df['status'] = status
    df['start_time'] = start_time
    df['end_time'] = end_time
    df['model_nickname'] = model_nickname
    df['n_features'] = n_feature
    df['n_samples'] = n_sample
    df['seed_dataset'] = seed
    df['fit_model_return_elapsed_time'] = no_run_time
    df['max_memory_used'] = no_run_memory
    df['EXCEPTION'] = EXCEPTION
    df['raised_exception'] = raised_exception
    df_cat.append(df)
    indexes.append(index)
df_no_run = pd.DataFrame(df_cat, index=indexes)
df_runs = pd.concat([df_runs, df_no_run])

In [96]:
# ensure no duplicates
df_runs = df_runs.loc[(~df_runs.duplicated(non_duplicate_columns))]

# Missing

In [97]:
df_runs['model_nickname'].unique().tolist()

['HDBSCAN', 'CoHiRF', 'IRFLLRR', 'KMeansProj', 'SpectralSubspaceRandomization']

In [98]:
non_duplicate_columns = [
    'model_nickname',
    'n_samples',
    'n_features',
    'seed_dataset',
]

In [99]:
n_samples = ['100', '347', '1202', '4163', '14427', '50000']
n_features = ['100', '347', '1202', '4163', '14427', '50000']
seeds_datasets = [str(i) for i in range(10)]
model_nickname = [
    'CoHiRF',
    'KMeans',
    'AffinityPropagation',
    'Clique',
    'SpectralClustering',
    'MeanShift',
    'SingleAgglomerativeClustering',
    'IRFLLRR',
    'CompleteAgglomerativeClustering',
    'KMeansProj',
    'HDBSCAN',
    'Proclus',
    'OPTICS',
    'SpectralSubspaceRandomization',
    'AverageAgglomerativeClustering',
    'DBSCAN',
    'WardAgglomerativeClustering'
]
columns_names = non_duplicate_columns
should_contain_values = [model_nickname, n_samples, n_features, seeds_datasets]
df_missing = get_missing_entries(df_runs, columns_names, should_contain_values)

In [100]:
df_missing

                   model_nickname n_samples n_features seed_dataset
0                          CoHiRF       100        100            1
1                          CoHiRF       100        100            2
2                          CoHiRF       100        100            3
3                          CoHiRF       100        100            4
4                          CoHiRF       100        100            5
...                           ...       ...        ...          ...
5823  WardAgglomerativeClustering     50000      50000            5
5824  WardAgglomerativeClustering     50000      50000            6
5825  WardAgglomerativeClustering     50000      50000            7
5826  WardAgglomerativeClustering     50000      50000            8
5827  WardAgglomerativeClustering     50000      50000            9

[5828 rows x 4 columns]

# Get common combinations

In [110]:
df_runs['model_nickname'].unique().tolist()

['HDBSCAN', 'CoHiRF', 'IRFLLRR', 'KMeansProj', 'SpectralSubspaceRandomization']

In [119]:
model_nickname = [
    'CoHiRF',
    'HDBSCAN',
    # 'KMeans',
    # 'Proclus',
    # 'AffinityPropagation',
    # 'Clique',
    # 'SpectralClustering',
    # 'MeanShift',
    # 'SingleAgglomerativeClustering',
    # 'IRFLLRR',
    # 'CompleteAgglomerativeClustering',
    # 'KMeansProj',
    # 'DBSCAN',
    # 'OPTICS',
    # 'SpectralSubspaceRandomization',
    # 'AverageAgglomerativeClustering',
    # 'WardAgglomerativeClustering'
]
df = df_runs.copy()
df = df.loc[df['model_nickname'].isin(model_nickname)]
column = 'model_nickname'
combination_columns = ['n_samples', 'n_features', 'seed_dataset']
common_combinations = get_common_combinations(df, column, combination_columns)

In [121]:
df_common = get_df_with_combinations(df, combination_columns, common_combinations)

In [122]:
df_common['n_samples'] = df_common['n_samples'].astype(int)
df_common['n_features'] = df_common['n_features'].astype(int)

In [123]:
df_common

,status,start_time,end_time,model_nickname,n_cores,n_features,n_jobs,n_samples,seed_dataset,fit_model_return_elapsed_time,max_memory_used,raised_exception,EXCEPTION
a2a179865078473a89620feec5df8b66,FINISHED,1.738176e+12,1.738176e+12,HDBSCAN,4,100,4,100,0,0.016728,331.852,False,NaN
d2395c43c6de4ecb872d9cb1b2363e13,FINISHED,1.738174e+12,1.738174e+12,CoHiRF,4,100,4,100,0,0.974811,334.748,False,NaN

# Plots

## Time

In [57]:
df = df_common.copy()
n_features = 14427
df = df.loc[df['n_features']==n_features]
df = df.loc[df['model_nickname'].isin(['CoHiRF', 'KMeans', 'HDBSCAN', 'DBSCAN', 'AffinityPropagation', 'OPTICS', 'SpectralSubspaceRandomization', 'WardAgglomerativeClustering'])]
df = df.sort_values(by='n_samples')
df = df.rename(columns={'fit_model_return_elapsed_time': 'Time (s)', 'max_memory_used': 'Memory (MB)', 'n_samples': 'Number of samples', 'n_features': 'Number of features', 'model_nickname': 'Model'})
fig = px.line(df, x='Number of samples', y='Time (s)', color='Model', line_dash='Model', log_x=True, log_y=True, markers=True, template='presentation', 
              category_orders={'Model': ['RecursiveClustering', 'KMeans', 'HDBSCAN', 'DBSCAN', 'AffinityPropagation', 'OPTICS', 'SpectralSubspaceRandomization', 'WardAgglomerativeClustering']})
# # transparent background
fig.update_layout({
    'font': {
        'color': 'black',
        'size': 15
    },
    'xaxis': {
        'color': 'black',
        'title': {'standoff': 15},
    }, 
    'yaxis': {
        'color': 'black',
    },
    'margin': {
        't': 10,
        'b': 50,
        'l': 50,
        'r': 30,
    },
    'legend': {
        'orientation': 'h',
        'yanchor': 'bottom',
        'y': 1.02,
        'xanchor': 'left',
        'x': 0.01,
        'title': {'text': ''}
    }
})
fig.update_xaxes(showline=True, mirror=True, dtick='D2')
fig.update_yaxes(showline=True, mirror=True, dtick='D2')
fig.show()
fig.write_image(f'time_n-samples_n-features{n_features}.pdf')

In [56]:
df = df_common.copy()
n_samples = 14427
df = df.loc[df['n_samples']==n_samples]
df = df.loc[df['model_nickname'].isin(['CoHiRF', 'KMeans', 'HDBSCAN', 'DBSCAN', 'AffinityPropagation', 'OPTICS', 'SpectralSubspaceRandomization', 'WardAgglomerativeClustering'])]
df = df.sort_values(by='n_features')
df = df.rename(columns={'fit_model_return_elapsed_time': 'Time (s)', 'max_memory_used': 'Memory (MB)', 'n_samples': 'Number of samples', 'n_features': 'Number of features', 'model_nickname': 'Model'})
fig = px.line(df, x='Number of features', y='Time (s)', color='Model', line_dash='Model', log_x=True, log_y=True, markers=True, template='presentation',
              category_orders={'Model': ['CoHiRF', 'KMeans', 'HDBSCAN', 'DBSCAN', 'AffinityPropagation', 'OPTICS', 'SpectralSubspaceRandomization', 'WardAgglomerativeClustering']})
# # transparent background
fig.update_layout({
    'font': {
        'color': 'black',
        'size': 15
    },
    'xaxis': {
        'color': 'black',
        'title': {'standoff': 15},
    }, 
    'yaxis': {
        'color': 'black',
    },
    'margin': {
        't': 10,
        'b': 50,
        'l': 50,
        'r': 30,
    },
    'legend': {
        'orientation': 'h',
        'yanchor': 'bottom',
        'y': 1.02,
        'xanchor': 'left',
        'x': 0.01,
        'title': {'text': ''}
    }
})
fig.update_xaxes(showline=True, mirror=True, dtick='D2')
fig.update_yaxes(showline=True, mirror=True, dtick='D2')
fig.show()
fig.write_image(f'time_n-features_n-samples{n_samples}.pdf')