In [2]:
from sqlalchemy import create_engine, text
import pandas as pd
from ml_experiments.analyze import get_df_runs_from_mlflow_sql, get_missing_entries, get_common_combinations, get_df_with_combinations
import plotly.express as px
from itertools import product
import time
import numpy as np
from pathlib import Path

# Save Results

## Load mlflow runs

In [3]:
db_path = Path().resolve().parent
db_name = 'ml_experiments.db'
url = f'sqlite:////{str(db_path)}/ml_experiments.db'
engine = create_engine(url)
query = 'SELECT experiments.name from experiments'
experiment_names = pd.read_sql(query, engine)['name'].tolist()
experiment_names

['Default', 'blob_time', 'hypercube_perf', 'real_perf']

In [4]:
experiment_names

['Default', 'blob_time', 'hypercube_perf', 'real_perf']

In [5]:
experiments_names = [
    'real_perf',
]

In [6]:
params_columns = [
    'model_nickname',
    'n_samples',
    'n_features',
    'n_classes',
    'seed_model',
    'dataset_id',
    'dataset_name',
    'direction',
    'hpo_metric',
    'standardize'
]

In [7]:
latest_metrics_columns = [
    'fit_model_return_elapsed_time',
    'max_memory_used',
    'n_clusters_',
    'rand_score',
    'adjusted_rand',
    'mutual_info',
    'adjusted_mutual_info',
    'normalized_mutual_info',
    'homogeneity',
    'completeness',
    'v_measure',
    'silhouette',
    'calinski_harabasz_score',
    'davies_bouldin_score',
    'inertia_score',
    'best_n_clusters_',
    'best_rand_score',
    'best_adjusted_rand',
    'best_mutual_info',
    'best_adjusted_mutual_info',
    'best_normalized_mutual_info',
    'best_homogeneity_completeness_v_measure',
    'best_silhouette',
    'best_calinski_harabasz_score',
    'best_davies_bouldin_score',
    'best_inertia_score',
    'best_homogeneity',
    'best_completeness',
    'best_v_measure',
]

In [8]:
tags_columns = [
    'raised_exception',
    'EXCEPTION',
    'parent_run_id',
    'best_child_run_id',
]

In [9]:
# parameters of each model, they are saved as tags for the parent run
parameters = {
    'CoHiRF': ['components_size', 'repetitions', 'kmeans_n_clusters'],
    'KMeans': ['n_clusters'],
    'HDBSCAN': ['min_cluster_size'],
    'DBSCAN': ['eps', 'min_samples'],
    'AffinityPropagation': ['damping'],
    'OPTICS': ['min_samples'],
    'SpectralSubspaceRandomization': ['n_similarities', 'sampling_ratio', 'sc_n_clusters'],
    'WardAgglomerativeClustering': ['n_clusters'],
}
all_model_parameters = [p for model, params in parameters.items() for p in params]
all_model_parameters = list(set(all_model_parameters))
for param in all_model_parameters:
    tags_columns.append(param)

In [10]:
runs_columns = ['run_uuid', 'status', 'start_time', 'end_time']
experiments_columns = []
other_table = 'params'
other_table_keys = params_columns
df_params = get_df_runs_from_mlflow_sql(engine, runs_columns=runs_columns, experiments_columns=experiments_columns, experiments_names=experiments_names, other_table=other_table, other_table_keys=other_table_keys)
df_latest_metrics = get_df_runs_from_mlflow_sql(engine, runs_columns=['run_uuid'], experiments_columns=experiments_columns, experiments_names=experiments_names, other_table='latest_metrics', other_table_keys=latest_metrics_columns)
df_tags = get_df_runs_from_mlflow_sql(engine, runs_columns=['run_uuid'], experiments_columns=experiments_columns, experiments_names=experiments_names, other_table='tags', other_table_keys=tags_columns)

In [11]:
df_runs_raw = df_params.join(df_latest_metrics)
df_runs_raw = df_runs_raw.join(df_tags)

In [12]:
df_runs_raw_parents = df_runs_raw.copy()
df_runs_raw_parents = df_runs_raw_parents.loc[df_runs_raw_parents['parent_run_id'].isna()]

In [13]:
# get all metrics beside best or last
metrics_columns = [
    'adjusted_rand',
    'silhouette',
    'calinski_harabasz_score',
    'davies_bouldin_score',
    'inertia_score',
]
metrics_columns_query = [f"'{m}'" for m in metrics_columns]
metrics_columns_query = ', '.join(metrics_columns_query)
experiments_names_query = [f"'{name}'" for name in experiments_names]
experiments_names_query = ', '.join(experiments_names_query)
query = f"""
SELECT
	runs.run_uuid,
	metrics."key",
	metrics.value,
	metrics.step 
FROM
	runs
LEFT JOIN metrics ON
	metrics.run_uuid = runs.run_uuid
LEFT JOIN experiments ON 
	experiments.experiment_id = runs.experiment_id  
WHERE 
	metrics."key" IN ({metrics_columns_query})
	AND experiments."name" IN ({experiments_names_query})
"""
df_metrics = pd.read_sql(query, engine)
df_metrics = df_metrics.pivot_table(index=['run_uuid', 'step'], columns='key', values='value')
df_metrics

,key,adjusted_rand,calinski_harabasz_score,davies_bouldin_score,inertia_score,silhouette
run_uuid,step,,,,,
01722f6a72d44cdf97bc5f562af90c80,0,0.565030,83.230517,1.234092,93.850387,0.244738
02fc6d201cd34facbb90359e44713233,0,0.440841,171.714093,1.108673,103.888127,0.286385
03193be7712c4c76acf185280f7d72b5,0,0.402983,43.672425,0.882544,41.365332,0.240700
0350e57dbca54dff965e4848146d217e,0,0.516233,77.227659,0.988128,83.288755,0.246147
04b7129bb5c94e7d9f26698d8e2efb4b,0,0.563751,141.815557,0.537022,203.450232,0.493991
...,...,...,...,...,...,...
f659c91046664bc0814ecf47d46eeba9,0,0.561078,138.300783,0.652959,155.135738,0.391244
f772126655714bf99c166f620901f72f,0,0.389894,80.134557,0.878873,44.398217,0.215247
f7e595c8ffd548fe9b7c07fb49ca10b0,0,0.538071,107.639403,1.073728,94.510648,0.286866
f80b2154d146417ca4179dd8e2f9ce86,0,0.506149,93.512662,1.300565,85.002866,0.318500
fd7046f729684231a1e130b06756c059,0,0.600075,105.070599,1.025058,128.219341,0.212082

In [14]:
df_runs_raw_parents

key,status,start_time,end_time,dataset_id,dataset_name,direction,hpo_metric,model_nickname,n_classes,n_features,...,rand_score,silhouette,v_measure,best_child_run_id,components_size,kmeans_n_clusters,min_cluster_size,parent_run_id,raised_exception,repetitions
run_uuid,,,,,,,,,,,,,,,,,,,,,
4a98bba749d548989c9fc4275de00146,FINISHED,1738176951842,1738176970691,61,iris,maximize,adjusted_rand,HDBSCAN,NaN,NaN,...,0.776644,0.493991,0.717464,e69af521ebba48ee920fea936120a329,NaN,NaN,5,NaN,False,NaN
d0d188ff68e74ed8918fc9a3e929ee36,FINISHED,1738174302391,1738174330687,61,iris,maximize,adjusted_rand,CoHiRF,NaN,NaN,...,0.776376,0.215247,0.561179,d83576b3c7974a349ab3bb46a2005c02,26,3,NaN,NaN,False,3

## Delete duplicate runs (if any) and complete some models that cannot run with some datasets

In [15]:
non_duplicate_columns = [
    'model_nickname',
    'dataset_id',
    'direction',
    'hpo_metric',
    'standardize',
]
df_runs_parents = df_runs_raw_parents.dropna(axis=0, how='all', subset=['best_adjusted_rand']).copy()
df_runs_parents = df_runs_parents.loc[(~df_runs_parents.duplicated(non_duplicate_columns))]

# Missing

In [16]:
df_runs_parents['model_nickname'].unique().tolist()

['HDBSCAN', 'CoHiRF']

In [17]:
non_duplicate_columns = [
    'model_nickname',
    'dataset_id',
    'direction',
    'hpo_metric',
    'standardize',
]

In [18]:
dataset_id = [40685, 39, 61, 182, 40984, 1478, 1568]
dataset_id = [str(d) for d in dataset_id]
direction = ['maximize']
metric = ['adjusted_rand']
standardize = ['True']
model_nickname = [
    'CoHiRF',
    'HDBSCAN',
    # 'CoHiRF_rbf',
    # 'WardAgglomerativeClustering',
    # 'KMeans',
    # 'DBSCAN',
    # 'SpectralSubspaceRandomization',
    # 'OPTICS',
    # 'KMeansProj',
    # 'IRFLLRR',
    # 'Clique',
    # 'SingleAgglomerativeClustering',
    # 'SpectralClustering',
    # 'Proclus',
    # 'CompleteAgglomerativeClustering',
    # 'AverageAgglomerativeClustering',
    # 'AffinityPropagation'
]
columns_names = non_duplicate_columns
should_contain_values = [model_nickname, dataset_id, direction, metric, standardize]
df_missing = get_missing_entries(df_runs_parents, columns_names, should_contain_values)

In [19]:
df_missing

   model_nickname dataset_id direction     hpo_metric standardize
0          CoHiRF      40685  maximize  adjusted_rand        True
1          CoHiRF         39  maximize  adjusted_rand        True
2          CoHiRF        182  maximize  adjusted_rand        True
3          CoHiRF      40984  maximize  adjusted_rand        True
4          CoHiRF       1478  maximize  adjusted_rand        True
5          CoHiRF       1568  maximize  adjusted_rand        True
6         HDBSCAN      40685  maximize  adjusted_rand        True
7         HDBSCAN         39  maximize  adjusted_rand        True
8         HDBSCAN        182  maximize  adjusted_rand        True
9         HDBSCAN      40984  maximize  adjusted_rand        True
10        HDBSCAN       1478  maximize  adjusted_rand        True
11        HDBSCAN       1568  maximize  adjusted_rand        True

# Plots

In [24]:
def get_parameters_string(row):
    parameter_names = {
        'components_size': 'q',
        'repetitions': 'R',
        'kmeans_n_clusters': 'C',
        'n_clusters': 'C',
        'min_cluster_size': 'C_{\\text{min}}',
        'eps': '\epsilon',
        'min_samples': 'n_{\\text{min}}',
        'damping': '\lambda',
        'n_similarities': 'm',
        'sampling_ratio': 'r',
        'sc_n_clusters': 'C',
    }
    first = True
    str = ''
    for p in all_model_parameters:
        if p in row:
            if not pd.isna(row[p]):
                if not first:
                    str += '; '
                else:
                    first = False
                value = float(row[p])
                if value.is_integer():
                    value = int(value)
                    str += f'${parameter_names[p]}={value}$'
                else:
                    str += f'${parameter_names[p]}={value:0.2f}$'
    return str

In [25]:
def highlight_max(df):
    max_values = df.groupby(level=0).transform('max')
    is_highlighted = df == max_values
    df_css = df.copy().astype(str)
    df_css.loc[:, :] = ''
    df_css[is_highlighted] = 'font-weight: bold'
    return df_css

In [28]:
df_runs_parents

key,status,start_time,end_time,dataset_id,dataset_name,direction,hpo_metric,model_nickname,n_classes,n_features,...,rand_score,silhouette,v_measure,best_child_run_id,components_size,kmeans_n_clusters,min_cluster_size,parent_run_id,raised_exception,repetitions
run_uuid,,,,,,,,,,,,,,,,,,,,,
4a98bba749d548989c9fc4275de00146,FINISHED,1738176951842,1738176970691,61,iris,maximize,adjusted_rand,HDBSCAN,NaN,NaN,...,0.776644,0.493991,0.717464,e69af521ebba48ee920fea936120a329,NaN,NaN,5,NaN,False,NaN
d0d188ff68e74ed8918fc9a3e929ee36,FINISHED,1738174302391,1738174330687,61,iris,maximize,adjusted_rand,CoHiRF,NaN,NaN,...,0.776376,0.215247,0.561179,d83576b3c7974a349ab3bb46a2005c02,26,3,NaN,NaN,False,3

In [29]:
datasets_ids = [40685, 39, 61, 182, 40984, 1478, 1568]
datasets_ids = [str(d) for d in datasets_ids]
models_nicknames = ['CoHiRF', 'KMeans', 'HDBSCAN', 'DBSCAN', 'AffinityPropagation', 'OPTICS', 'SpectralSubspaceRandomization', 'WardAgglomerativeClustering']
df = df_runs_parents.copy()
df = df.loc[df['dataset_id'].isin(datasets_ids)]
df = df.loc[df['model_nickname'].isin(models_nicknames)]
df['Parameters'] = df.apply(get_parameters_string, axis=1)
df = df[['model_nickname', 'dataset_name', 'best_adjusted_rand', 'Parameters']]
models_names = {
    'CoHiRF': 'CoHiRF',
    'KMeans': 'K-Means',
    'HDBSCAN': 'HDBSCAN',
    'DBSCAN': 'DBSCAN',
    'AffinityPropagation': 'Affinity Propagation',
    'OPTICS': 'OPTICS',
    'SpectralSubspaceRandomization': 'SC-SRGF',
    'WardAgglomerativeClustering': "Ward's Method",
}
parameters = {
    'RecursiveClustering': ['components_size', 'repetitions', 'kmeans_n_clusters'],
    'KMeans': ['n_clusters'],
    'HDBSCAN': ['min_cluster_size'],
    'DBSCAN': ['eps', 'min_samples'],
    'AffinityPropagation': ['damping'],
    'OPTICS': ['min_samples'],
    'SpectralSubspaceRandomization': ['n_similarities', 'sampling_ratio', 'sc_n_clusters'],
    'WardAgglomerativeClustering': ['n_clusters'],
}
df = df.replace({'model_nickname': models_names})
df = df.rename(columns={'best_adjusted_rand': 'ARI', 'model_nickname': 'Model', 'dataset_name': 'Dataset'})
df = df.groupby(['Dataset', 'Model']).agg({'ARI': 'mean', 'Parameters': 'first'})

In [30]:
df

key                   ARI            Parameters
Dataset Model
iris    CoHiRF   0.704027  $C=3$; $q=26$; $R=3$
        HDBSCAN  0.563751    $C_{\text{min}}=5$

In [31]:
print(df.style.apply(highlight_max, subset='ARI', axis=None).format(precision=3, na_rep='No Run').to_latex(hrules=True, clines='skip-last;data', convert_css=True, column_format='p{1cm}lp{0.5cm}l'))

\begin{tabular}{p{1cm}lp{0.5cm}l}
\toprule
 & key & ARI & Parameters \\
Dataset & Model &  &  \\
\midrule
\multirow[c]{2}{*}{iris} & CoHiRF & \bfseries 0.704 & $C=3$; $q=26$; $R=3$ \\
 & HDBSCAN & 0.564 & $C_{\text{min}}=5$ \\
\cline{1-4}
\bottomrule
\end{tabular}